# Import file with secret info like userkey / apikey for pushover
variables: secrets.yml

# define templates to use into our tasks
# We will use deluge instead of transmission / ... => https://flexget.com/Plugins/deluge
templates:
  global:
    # pushover configuration => https://flexget.com/Plugins/Notifiers/pushover
    notify:
      entries:
        title: 'Downloading {{series_name}}'
        message: 'Episode {{series_id}}'
        via:
          - pushover:
              user_key: '{? pushover.userkey ?}'
              api_key: '{? pushover.apikey ?}'
              device: mobile
              priority: 2

  # configure anime template, we will need to list our shows or use a plugin like https://github.com/edhaker13/myanimelist
  anime:
    exists_series:
      path: '/home/deluge/torrents/series/{{series_name}}/'
      allow_different_qualities: better
    series:
      - serie 1
      - serie 2
      - serie 3
    set:
      path: '/home/deluge/torrents/series/{{series_name}}/'
    deluge: yes

tasks:
  nyaa_horrible_subs:
    # define our rss url
    rss: 'https://nyaa.si/?page=rss&c=1_2&f=0&q=horriblesubs'
    no_entries_ok: yes
    quality:
      720p-1080p
    template:
      - anime
    # set a priority => https://flexget.com/Plugins/priority
    priority: 1

  nyaa_en_all:
    # define our rss url
    rss: 'https://nyaa.si/?page=rss&c=1_2&f=0'
    no_entries_ok: yes
    # We can't use quality to find our animes since some titles don't contain "720p" or 1080p but HD / FHD
    content_size:
      min: 250
    template:
      - anime
    # set a priority => https://flexget.com/Plugins/priority
    priority: 2

# schedules
# Used to specify interval
# '*' means every task
schedules:
  - tasks: '*'
    interval:
      hours: 1
